spring:
  datasource:
#    url: jdbc:mariadb://localhost:3306/springbootlevel1user
#    uesrname: magicuser
#    password: 1234
#    driver-class-name: org.mariadb.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/springbootlevel1user?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: magicuser
    password: 1234

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: true